theme = "gruvbox-light"
icons = "awesome"

[[block]]
block = "bluetooth"
mac = "94:DB:56:63:A6:18"
format = "WH-1000XM4"
format_unavailable = "WH-1000XM4"
[block.theme_overrides]
idle_bg = "#ffffff"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
